import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import {ReactNode} from "react";
import "@/shared/styles/main.css";
import {ThemeSwitch, Toaster} from "@/shared/components";

const nunito = Nunito({
    subsets: ['cyrillic'],
    variable: '--font-nunito',
    weight: ['500', '600', '700', '900'],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en">
        <body className={nunito.variable}>
        <ThemeSwitch/>
        {children}
        <Toaster position="top-center" />
        </body>
        </html>
    );
}
